### ISSUE TITLE
how do I open the ldb files

### ISSUE THREAD

**Issue by RedsLovesGames** [Takaovi/BatchStealer#4]

**Comment by Takaovi** [comment]
I've just opened them with Notepad++ and then searched for the Token. (It's on the last line)

**Comment by RedsLovesGames** [comment]
![image](https://user-images.githubusercontent.com/75150137/126556143-47569bbb-8026-4042-a40c-c682a7f71f85.png)

**Comment by Takaovi** [comment]
Just ignore the white boxes,
1. CTRL + F
2. Search `Token`
3. Look for `mfa.1-` and if you find it, it's the token.

I guess I could quickly create a tool for this if you'd like.

**Comment by RedsLovesGames** [comment]
please do

**Comment by Takaovi** [comment]
Either I am tripping balls, or Discord has changed the way they store tokens?

Can you reinstall Discord (Also remove the Discord folder from `%appdata%\discord\Local Storage\leveldb`) ,
then do CTRL + R,  `%appdata%\discord\Local Storage\leveldb` and see if you have any .ldb files?

**Comment by RedsLovesGames** [comment]
yep I see ldb files

**Comment by Takaovi** [comment]
I don't anymore, strange. Feel free to add me on Discord `Takaovi#0227` if you want to discuss this further.

**Comment by RedsLovesGames** [comment]
added

**Comment by Takaovi** [comment]
To anyone wondering the same question, feel free to use my tool, https://github.com/Takaovi/DscLdbExtr.

It is working currently (28/07/2021) but will not work if Discord changes the layout of the file.

**Comment by Takaovi** [comment]
If you have issues with the tool, feel free to make an issue to the repo, but not to here. Thank you!
